### ISSUE TITLE
No undo history after installing brackets-file-tree-exclude

### ISSUE THREAD

**Issue by pnylon** [zaggino/file-tree-exclude#1]
Hello, I noticed that I lost my undo history so I started testing one extension at a time. So far it is looking like brackets-file-tree-exclude is the cause.

First I checked them individually using this method.
https://github.com/adobe/brackets/wiki/Troubleshooting#disabling-extensions-individually

This is what I did for testing brackets-file-tree-exclude.
1. I disabled and removed all the extensions.
2. Added and enabled brackets-file-tree-exclude.
3. Tested a couple saves and then undo. It was OK.
4. Quit and restarted Brackets.
5. Tested a couple saves and then undo. Undo not working.

**Comment by pnylon** [comment]
Apparently this problem is happening a lot in Brackets, but for me I only experience it when this extension is installed. Anyway, it seems nobody knows what the cause is yet.

**Comment by zaggino** [comment]
This is definitely related to another extension, I have this extension installed and undo always works fine. Check for extensions that do changes to your files (like cleaning a whitespace or fixing indentation). Reloading external changes to a file causes Brackets to lose undo history sometimes.
