### ISSUE TITLE
Not all folder are being excluded

### ISSUE THREAD

**Issue by thany** [zaggino/file-tree-exclude#2]
It's actually the exact same issue as the [one filed at JonathanWolfe's](https://github.com/JonathanWolfe/file-tree-exclude/issues/30) go at an extension like this...

Only in this case the config looks like this, following the way it is in the documentation:

``` javascript
"brackets-file-tree-exclude.excludeList": [
  "/bower_components/",
  "/node_modules/",
  "/.git/",
  "/.sass-cache/",
  "/.tmp/"
]
```

**Comment by zaggino** [comment]
It works fine for me, just tested. There was a bug - it required you to switch project or restart Brackets to take effect but that should also be fixed in version `1.0.4`
