### ISSUE TITLE
cannot index instant search after update

### ISSUE THREAD

**Issue by sweatherall** [zaggino/file-tree-exclude#3]
I just updated this plug-in and now when I try to do a search on all files I get a spinning "indexing for Instant Search" for a very long time. (left for 20 minutes, came back, still spinning)
I am using Brackets 1.5
Before the update this plugin was working great!

Any tips ?

**Comment by zaggino** [comment]
are the excluded folders showing in the file tree on the left?

**Comment by sweatherall** [comment]
They are not showing in the file tree.

**Comment by zaggino** [comment]
then the extension seems to be working fine

**Comment by sweatherall** [comment]
OK. I hope I can nail the issue then.
Another thing that is different than before is that on initial opening of Brackets, I get an "Error Indexing Files - this project contains more than 30,000 files." After accepting this error message, and proceeding to open brackets, the folders are hidden like the extension is supposed to do.

When I would use the extension before, I would _not_ get this error upon opening brackets. It seems like if the extension is working with the updated version of Brackets as it was working before, I should not be getting this message upon opening the application. Is this indicative of anything going wrong?

**Comment by zaggino** [comment]
What probably happens is that for some reason, the extension is loaded after the indexing had already started. I'd have to check if the indexing waits for all extensions to be loaded or not.

**Comment by zaggino** [comment]
@abose @nethip can you confirm that indexing waits until all the extensions are loaded (and changes to file exclusion can be made) or does it start to index immediatelly after project is opened?

By looking at this https://github.com/adobe/brackets/blob/master/src/search/FindInFiles.js#L922 it seems that the indexing starts immediately.

**Comment by sweatherall** [comment]
After more testing, I noticed after I pressed enter in the 'search all files bar', it said that my filter excludes all files in my project.
<img width="832" alt="screen shot 2016-01-03 at 6 54 07 pm" src="https://cloud.githubusercontent.com/assets/4127588/12081573/9b54cbf0-b24b-11e5-85fe-a2260140fdf8.png">

and when I enter the 'Edit Exclusion Set' settings it says I have 0 files in my project.
<img width="603" alt="screen shot 2016-01-03 at 6 53 53 pm" src="https://cloud.githubusercontent.com/assets/4127588/12081583/c6a47d28-b24b-11e5-9614-1fc02ba4d5e4.png">

**Comment by abose** [comment]
https://github.com/adobe/brackets/blob/master/src/search/node/FindInFilesDomain.js#L367
indexing happens 1 second after project switch.
The first index is 5 seconds after appready.

**Comment by zaggino** [comment]
0 of 0 files in project seems like something else than problem of this extension... do you see anything at all in the file tree?

**Comment by abose** [comment]
can you check for any console logs from `debug>show developer tools`

**Comment by sweatherall** [comment]
There didn't seem to be any logs pertaining to this issue when I thought to check before.
I was seeing all of my other project folders besides the ones that were being (accurately) hidden.

I implemented a last resort solution just yesterday: I completely uninstalled brackets and removed all the cached folders/files found in /Library/Application Support/Brackets.
Then I reinstalled Brackets and all of my plugins.

Like I said, it was a last resort, but this worked. 
Thank you for the help!

**Comment by webtrad3r** [comment]
it happened to me after i messed up with indexing of files in windows. type in your search bar indexing open the app and reset it to default values. same in control panel add remove programs set to default values. restart it should work. then where you get that error with searching as forever, just press on it, the find files bar should pop up underneath the Brackets software (as we all know/as usual)

kindest
Georgian

**Comment by cmarydai** [comment]
Has this been fixed? I am getting this problem now

**Comment by sweatherall** [comment]
It was a while ago, but if I remember correctly, I had to uninstall
brackets completely, delete all the hidden preference files, and then
reinstall everything :/ and then it worked.
In theory, just deleting the hidden preference files should do it, so maybe
try that first. (I forget where those files were exactly)

Sorry if thats not much help, I hope you figure it out.
