### ISSUE TITLE
[question] Leaving 'dist' folder available by default?

### ISSUE THREAD

**Issue by vankasteelj** [zaggino/file-tree-exclude#5]
By default, you hide `/dist`, and I think it's unnecessary. For example, I use /dist to store my distribution-related scripts, which I'd like to access from brackets. 

I know I can remove it (and I did), but I'm now questionning the advantage of having that specific folder on by default.

Just asking you to consider the question. Thanks

**Comment by isherwood** [comment]
Normally dist build directories aren't modified once the build is complete, and they're often not checked into version control. It's probably rare that a developer would want to see that directory in the normal course of work.
