### ISSUE TITLE
How exclude by begin path?

### ISSUE THREAD

**Issue by doiftrue** [zaggino/file-tree-exclude#7]
I need exclude `/plugins` but not `/some_dir/plugins`. Is it possible? All my attempts are failed...

**Comment by zaggino** [comment]
Probably not without fixing the code

**Comment by doiftrue** [comment]
I dont know why but now construction like `/plugins` exclude only path begin with plugins, and `/plugins/` exclude path contain plugin...

Now problem is solved, all works perfectly!

**Comment by doiftrue** [comment]
Oh, no - not work correctry...

**Comment by zaggino** [comment]
You can update to `1.1.0` and use:
```
"brackets-file-tree-exclude.excludeList": [
    "^plugins/"
  ]
```
`^` symbolizes project root

**Comment by doiftrue** [comment]
wow, so many thanks !!! Now it works perfectly!
